const USER_EVENTS = {
	LOGO_CLICK: 'user_clicked_logo',
	SIDE_MENU_CLICK: 'user_side_menu_clicked',
	GET_OTP: 'user_clicked_get_otp',
	DATE_CLICK: 'date_item_clicked',
	FILTER_ITEM: 'filter_item_clicked',
	CALENDER_ICON: 'calender_icon_clicked',
	UPLOAD_RECORD_SIDEBAR: 'upload_medical_record_sidebar',
	MEDICAL_RECORD_DELETE_MODAL: 'delete_medical_record_modal',
	MEDICAL_RECORD_DELETE: 'delete_medical_record',
	MEDICAL_RECORD_DOWNLAOD: 'download_medical_record',
	COMMENT_SUBMIT: 'user_comment_submitted',
	USER_PROFILE_IMAGE: 'user_profile_image_submitted',
	USER_PROFILE_TAB: 'user_profile_tab_clicked',
	SEARCH_PET_PARENT_ITEM_SUGGESTION: 'search_pet_parent_suggestion_clicked',
	SEARCH_PET_PARENT_CLEAR: 'search_pet_parent_clear',
	SEARCH_PET_PARENT_ADD_PARENT_MODAL: 'search_pet_parent_add_parent_modal',
	PARENT_EDIT_PROFILE_IMAGE: 'parent_edit_profile_image',
	PARENT_MODAL: 'parent_modal',
	PET_MODAL: 'pet_modal',
	PARENT_PET_CLICK: 'parent_pet_click',
	HEADER_PROFILE_USER_ICON: 'header_profile_user_icon_click',
	HEADER_PROFILE_LOGOUT_ICON_MODAL: 'header_profile_logout_icon_click_modal',
	PET_PROFILE_IMAGE_CLICK: 'pet_profile_image_click',
	PET_PROFILE_TABS: 'pet_profile_tabs',
};

export { USER_EVENTS };
